### ISSUE TITLE
in windows run fail

### ISSUE THREAD

**Issue by Miofly** [antfu/vitesse-nuxt-bridge#15] opened 2023-07-31 06:48 UTC
### Describe the bug

windows run pnpm dev fail
![image](https://github.com/antfu/vitesse-nuxt-bridge/assets/42859910/7d62c812-8ac5-4f98-a511-ad76fd67435d)

### Reproduction

null

### System Info

```Shell
System:                                                     
    OS: Windows 10 10.0.19044                                 
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz    
    Memory: 4.22 GB / 15.76 GB                                
  Binaries:                                                   
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE          
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD          
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD             
    pnpm: 8.6.9 - C:\Program Files\nodejs\pnpm.CMD            
  Browsers:                                                   
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-07-31 10:46
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2023-07-31 10:46 UTC
